site_name: FakerPHP / Faker
site_description: Documentation for FakerPHP / Faker

theme:
  name: material
  palette:
    scheme: preference
  language: en

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FakerPHP/Faker
      name: Faker